name: Docker Image web-server CI

on:
  push:
    branches: [ "featlmkj-build-test" ]
  pull_request:
    branches: [ "featlmkj-build-test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ web-server-experimental ]

    env:
      ALIYUN_REGISTRY_URL: registry.cn-hangzhou.aliyuncs.com
      ALIYUN_NAMESPACE: limch
      ALIYUN_USERNAME: tb921193_33
      ALIYUN_PASSWORD: lmlmlmlm8
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build APITable and Push
        run: |
          eval "$(./scripts/semver-ci.sh)"
          make buildpush-docker-new target=${{ matrix.target }}
