name: Docker Image room-server CI

on:
  push:
    branches: [ "feat/lmkj" ]
  pull_request:
    branches: [ "feat/lmkj" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      env:
        ALIYUN_REGISTRY_URL: registry.cn-hangzhou.aliyuncs.com
        ALIYUN_NAMESPACE: lmkj-test
        ALIYUN_REPO_NAME: apitable-room-server
        ALIYUN_USERNAME: tb921193_33
        ALIYUN_PASSWORD: lmlmlmlm8
      run: |
        docker login --username $ALIYUN_USERNAME --password $ALIYUN_PASSWORD $ALIYUN_REGISTRY_URL/$ALIYUN_NAMESPACE
        docker build . --file packaging/Dockerfile.room-server --tag $ALIYUN_REGISTRY_URL/$ALIYUN_NAMESPACE/$ALIYUN_REPO_NAME:latest
        docker push $ALIYUN_REGISTRY_URL/$ALIYUN_NAMESPACE/$ALIYUN_REPO_NAME:latest
        